export { default as HeroSection } from "./HeroSection";
export { default as AboutSection } from "./AboutSection";
export { default as ServicesSection } from "./ServicesSection";
export { default as ConstructionsSection } from "./ConstructionsSection";
export { default as PricingSection } from "./PricingSection";
export { default as StepsSection } from "./StepsSection";
export { default as EquipmentSection } from "./EquipmentSection";
export { default as ProjectsSection } from "./ProjectsSection";
export { default as ClientsSection } from "./ClientsSection";
